apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "helm-project-operator.name" . }}
  labels: {{ include "helm-project-operator.labels" . | nindent 4 }}
    app: {{ template "helm-project-operator.name" . }}
rules:
# Helm Project Operator
- apiGroups:
  - helm.cattle.io
  resources:
  - projecthelmcharts
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - get
  - list
  - watch
# Helm Controller
- apiGroups:
  - helm.cattle.io
  resources:
  - helmcharts
  verbs:
  - "*"
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - "*"
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - serviceaccounts
  verbs:
  - "*"
# Helm Locker
- apiGroups:
  - helm.cattle.io
  resources:
  - helmreleases
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - watch
# Common
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - "*"
- apiGroups:
    - ""
    - events.k8s.io
  resources:
    - events
  verbs:
    - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "helm-project-operator.name" . }}
  labels: {{ include "helm-project-operator.labels" . | nindent 4 }}
    app: {{ template "helm-project-operator.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "helm-project-operator.name" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "helm-project-operator.name" . }}
  namespace: {{ template "helm-project-operator.namespace" . }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "helm-project-operator.name" . }}
  namespace: {{ template "helm-project-operator.namespace" . }}
  labels: {{ include "helm-project-operator.labels" . | nindent 4 }}
    app: {{ template "helm-project-operator.name" . }}
{{- if .Values.global.imagePullSecrets }}
imagePullSecrets: {{ toYaml .Values.global.imagePullSecrets | nindent 2 }}
{{- end }}
