apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config-map
  namespace: {{ .Release.Namespace }}
data:
  config: |-
{{ .Values.data | toYaml | indent 4 }}
  project-namespaces: |-
{{ .Values.global.cattle.projectNamespaces | toYaml | indent 4 }}
  project-id: |-
{{ .Values.global.cattle.projectID | toYaml | indent 4 }}
  system-project-id: |-
{{ .Values.global.cattle.systemProjectID | toYaml | indent 4 }}
  project-namespace-selector: |-
{{ .Values.global.cattle.projectNamespaceSelector | toYaml | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config-map-2
  namespace: {{ .Release.Namespace }}
data:
  config: |-
{{ .Values.data | toYaml | indent 4 }}
  project-namespaces: |-
{{ .Values.global.cattle.projectNamespaces | toYaml | indent 4 }}
  project-id: |-
{{ .Values.global.cattle.projectID | toYaml | indent 4 }}
  system-project-id: |-
{{ .Values.global.cattle.systemProjectID | toYaml | indent 4 }}
  project-namespace-selector: |-
{{ .Values.global.cattle.projectNamespaceSelector | toYaml | indent 4 }}